default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-added-large-files
        args:
          - --maxkb=1024
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.26
    hooks:
      - id: actionlint
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - id: ruff

exclude: |
  (?x)(
    /(
      \.git
      | \.mypy_cache
      | \.pytest_cache
      | \.ruff_cache
      | \.venv
      | venv
    )/
  )
